services:
  db:
    image: postgis/postgis:15-3.3
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aero
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/aero
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/backend
    restart: unless-stopped

volumes:
  db-data:
